[config]

[templates.gtk3]
input_path = './templates/gtk-colors.css'
output_path = '~/.config/gtk-3.0/dank-colors.css'

[templates.gtk4]
input_path = './templates/gtk-colors.css'
output_path = '~/.config/gtk-4.0/dank-colors.css'

[templates.qt5ct]
input_path = './templates/qtct-colors.conf'
output_path = '~/.config/qt5ct/colors/matugen.conf'

[templates.qt6ct]
input_path = './templates/qtct-colors.conf'
output_path = '~/.config/qt6ct/colors/matugen.conf'

[templates.kcolorscheme]
input_path = './templates/matugen-kcolorscheme.colors'
output_path = '~/.local/share/color-schemes/DankMatugen.colors'

[templates.dgop]
input_path = './templates/dgop.json'
output_path = '~/.config/dgop/colors.json'

[templates.niri]
input_path = './templates/niri-colors.kdl'
output_path = '~/.config/niri/dankshell-colors.kdl'

[templates.ghostty]
input_path = './templates/ghostty-colors.conf'
output_path = '~/.config/ghostty/config-dankcolors'